---
# tasks file for GoKEV-lab-installtower

- name: Check if Tower is running and responding
  uri:
    url: https://localhost/api/v1/ping/
    method: GET
    user: admin
    password: "{{ towerpass }}"
    validate_certs: False
  register: tower_ping
  failed_when: False

- name: set condtional if the above didn't error
  set_fact:
    tower_ver: "{{ tower_ping.json.version }}"
  when: tower_ping.json is defined

- name: Clears install directory
  file:
    path: /root/ansible-installer/
    state: absent
  when: tower_ver is not defined

- name: Creates install directory
  file:
    path: /root/ansible-installer/
    state: directory
  when: tower_ver is not defined

- name: Grab the latest Tower installer
  unarchive:
    src: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
    dest: /root/ansible-installer/
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: tower_ver is not defined


- name: Set some passwords in the inventory file
  lineinfile:
    path: /root/ansible-installer/inventory
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^admin_password=", line: "admin_password='{{ towerpass }}'" }
    - { regexp: "^pg_password=", line: "pg_password='{{ towerpass }}'" }
    - { regexp: "^rabbitmq_password=", line: "rabbitmq_password='{{ towerpass }}'" }
  when: tower_ver is not defined

- name: Strip out preflight from running
  lineinfile:
    path: /root/ansible-installer/install.yml
    state: absent
    regexp: '^.*preflight.*$'
  when: tower_ver is not defined

- name: run the tower installer
  shell: ./setup.sh
  args:
    chdir: /root/ansible-installer/
  when: tower_ver is not defined

- name: wait for tower to be up
  uri:
    url: https://localhost/api/v1/ping/
    method: GET
    user: admin
    password: redhat
    validate_certs: False
    force_basic_auth: yes
  register: check2
  until: check2.json is defined
  retries: 10
  delay: 30
  when: tower_ver is not defined

- name: Post license key
  uri:
    url: https://localhost/api/v1/config/
    method: POST
    user: admin
    password: "{{ towerpass }}"
    body: "{{ lookup('file','files/tower-license.json') }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes
  ignore_errors: True

- name: Clears install directory
  file:
    path: /root/ansible-installer/
    state: absent

- debug:
    msg: "This system {{ inventory_hostname }} is running with Ansible Tower version {{ tower_ver }}"
  when: tower_ver is defined

